title: Juan Bernardo Tobar - Blockchain Engineer and Founder of ADOM Inc.
description: Own your data, your identity, your money - download MAIA wallet.  - What Netscape did for the Internet, MAIA does for the blockchain - but from your smartphone.


plugins:
  - jekyll-seo-tag

theme: minima
